
trigger:
  - none

parameters:
  - name: siteEnvPrefixLocal
    type: string
  - name: siteId
    type: string
  - name: siteFarmId
    type: string
  - name: branch
    type: string
  - name: azureServiceConnection
    type: string
  - name: dockerRegistryServiceConnection
    type: string
  - name: imageRepository
    type: string
  - name: containerRegistry
    type: string

pool:
  vmImage: 'ubuntu-22.04'

stages:

    - stage: Deploy
      displayName: Deploy
      dependsOn: Build
      condition: succeeded('Build')
      jobs:
        - job: Deploy
          displayName: Deploy to App Service
          steps:
            - task: AzureWebAppContainer@1
              displayName: '-- Push latest container'
              inputs:
                azureSubscription: ${{azureServiceConnection}}
                appName: '${{siteEnvPrefixLocal}}-ctcms-ct${{siteId}}-app'
                resourceGroupName: '${{siteEnvPrefixLocal}}-ctcms-df${{siteFarmId}}-app-rg'
                containers: '$(containerRegistry)/$(imageRepository):latest'
