trigger:
  branches:
    include:
      - master
  paths:
    include:
      - test-pipeline-approve-private-endpoint.yml

name: $(Build.BuildId)

parameters:
  - name: azureServiceConnection
    type: string
    default: 'UAT Resource Manager'
  - name: siteEnvPrefixLocal
    type: string
    default: 'uat'
  - name: siteFarmId
    type: string
    default: '3'
  - name: siteId
    type: string
    default: '9301'
  - name: uniqueMod
    type: string
    default: '1'

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    displayName: '-- Approve Private Endpoint'
    inputs:
      azureSubscription: '${{parameters.azureServiceConnection}}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $subscriptionInfo = az account show | ConvertFrom-Json
        $privateEndpoints = az network private-endpoint-connection list --id /subscriptions/$($subscriptionInfo.id)/resourceGroups/${{parameters.siteEnvPrefixLocal}}-ctcms-df${{parameters.siteFarmId}}-app-rg/providers/Microsoft.Web/sites/${{parameters.siteEnvPrefixLocal}}-ctcms-ct${{parameters.siteEnvPrefixLocal}}${{parameters.siteId}}-app${{parameters.uniqueMod}} | ConvertFrom-Json
        $privateEndpoints | FT
        az network private-endpoint-connection approve --id  /subscriptions/$($subscriptionInfo.id)/resourceGroups/${{parameters.siteEnvPrefixLocal}}-ctcms-df${{parameters.siteFarmId}}-app-rg/providers/Microsoft.Web/sites/${{parameters.siteEnvPrefixLocal}}-ctcms-ct${{parameters.siteEnvPrefixLocal}}${{parameters.siteId}}-app${{parameters.uniqueMod}}/privateEndpointConnections/6ffd1f8c-57da-412c-bfda-182ace4fe8f9-949243ba-a927-459e-a9a9-40161e331eb5 --description "Approved"
