parameters:
  - name: azureServiceConnection
    type: string
    default: ''
  - name: siteEnvPrefixLocal
    type: string
    default: ''
  - name: resourceGroupName
    type: string
    default: ''
  - name: location
    type: string
    default: ''
  - name: siteFarmId
    type: string
    default: ''
  - name: siteId
    type: string
    default: ''
  - name: siteName
    type: string
    default: ''
  - name: uniqueMod
    type: string
    default: ''
  - name: buildId
    type: string
    default: ''

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: '-- Provision App Service'
    inputs:
      deploymentScope: 'Subscription'
      azureResourceManagerConnection: '${{parameters.azureServiceConnection}}'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '${{parameters.siteEnvPrefixLocal}}${{parameters.resourceGroupName}}'
      location: '${{parameters.location}}'
      templateLocation: 'Linked artifact'
      csmFile: './.devops/site-build.bicep'
      overrideParameters: '-siteFarmId ${{parameters.siteFarmId}} -siteId ${{parameters.siteId}} -env ${{parameters.siteEnvPrefixLocal}} -siteName ${{parameters.siteName}} -uniqueMod ${{parameters.uniqueMod}}'
      deploymentMode: 'Incremental'
      deploymentName: 'DeployPipelineTemplate-${{parameters.siteId}}-${{parameters.buildId}}'
