trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .devops/adm-rg.bicep
      - .devops/app-rg.bicep
      - .devops/site-build.bicep
      - .devops/role-assign.bicep
      - .devops/pipeline/_deploy-container.yml
      - .devops/pipeline/_provision-app-service.yml
      - .devops/pipeline/azure-pipelines-infrastructure.yml
      - .devops/pipeline/azure-pipelines-release-infrastructure.yml

resources:
  - repo: self

pool:
  vmImage: 'ubuntu-22.04'

name: $(Build.BuildId)

parameters:
  - name: sites
    type: object
    default:
      - sacramento|1|100
      - stanislaus|1|101
      - butte|1|102
      - humboldt|1|103
      - merced|1|104
      - siskiyou|1|105
      - nccourt|1|106
      - tehama|1|107
      - sierra|1|108
      - sanbenito|1|109
  - name: sites_1
    type: object
    default:
      - glenn|1|110
      - supremecourt|1|111
      - fresno|1|112
      - newsroom|1|113
      - sf|2|200
      - santabarbara|2|201
      - riverside|2|202
      - partners|2|203
      - oc|2|204
      - mendocino|2|205
  - name: sites_2
    type: object
    default:
      - monterey|2|206
      - slo2|2|207
      - sc|2|208
      - madera|2|209
      - napa|2|210
      - inyo|2|211
      - mariposa|2|212
      - alpine|2|213
      - tuolumne|2|214
      - deprep|2|215
  - name: sites_3
    type: object
    default:
      - alameda|2|216
      - kern|2|217
      - tularesuperiorcourt|2|218
      - sonoma|3|300
      - eldorado|3|301
      - imperial|3|302
      - kings|3|303
      - sutter|3|304
      - mono|3|305
  - name: sites_4
    type: object
    default:
      - colusa|3|306
      - modoc|3|307
      - yuba|3|308
      - trinity|3|309
      - srl|3|310
      - elcondado|3|311
      - idm|3|312
      - amdr|3|313
      - lake|3|314
#  - name: sites_5
#    type: object
#    default:

variables:
  imageRepository: 'build/trialcourt/$(Build.SourceBranchName)'
  dockerfilePath: '$(Build.SourcesDirectory)/.devops/drupal-nginx-fpm/0.6-devops/Dockerfile'
  containerRegistry: 'globalctcmscr.azurecr.io'
  tag: 'build_$(Build.BuildId)-$(Build.SourceVersion)'
  location: 'West US 3'
  site: ''
  siteId: ''
  siteName: ''
  siteFarmId: ''
  siteEnvPrefix: ''
  ResourceGroupName: ''
  uniqueMod: '1'

  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    azureServiceConnection: 'UAT Resource Manager'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'stage') }}:
    azureServiceConnection: 'UAT Resource Manager'
  ${{ else }}:
    azureServiceConnection: 'INT resource Manager'

stages:

  - stage: Manifest
    displayName: Manifest
    jobs:
      - job: ReadManifest
        displayName: Read manifest file
        steps:
          - script: |
              case $(Build.SourceBranchName) in
                master)
                  echo "##vso[task.setvariable variable=siteEnvPrefix;isOutput=true;]uat"
                  ;;
                stage)
                  echo "##vso[task.setvariable variable=siteEnvPrefix;isOutput=true;]uat"
                  ;;
                *)
                  echo "##vso[task.setvariable variable=siteEnvPrefix;isOutput=true;]int"
                  ;;
              esac
            displayName: 'Set Environment Prefix'
            name: EnvironmentPrefix
          - script: echo "$(EnvironmentPrefix.siteEnvPrefix)"
            displayName: 'Display Prefix'

      - job: ProcessSites
        displayName: Process sites
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - script: |
              rm -rf $(Build.ArtifactStagingDirectory)/manifest.txt
              touch $(Build.ArtifactStagingDirectory)/manifest.txt

              rm -rf $(Build.ArtifactStagingDirectory)/build-image.txt
              echo $(tag) > $(Build.ArtifactStagingDirectory)/build-image.txt

              cp -r $(Build.SourcesDirectory)/.devops/scripts/trigger-release-infrastructure-pipeline.ps1 $(Build.ArtifactStagingDirectory)
            displayName: 'Initialize drop files'

          - ${{ each site in parameters.sites }}:
            - script: |
                IFS='|'
                read -a siteInfo <<< "${{site}}"

                echo "CountyId: ${siteInfo[0]}"
                echo "CountyName : ${siteInfo[2]}"
                echo "FarmId : ${siteInfo[1]}"
                echo "##vso[task.setvariable variable=site;]${{site}}"
                echo "##vso[task.setvariable variable=siteId;]${siteInfo[2]}"
                echo "##vso[task.setvariable variable=siteFarmId;]${siteInfo[1]}"
                echo "##vso[task.setvariable variable=siteName;]${siteInfo[0]}"
                echo "##vso[task.setvariable variable=ResourceGroupName;]-ctcms-df${siteInfo[1]}-app-rg"
              displayName: 'SITE: ${{ site }}'

            - template: /.devops/pipeline/_provision-app-service.yml
              parameters:
                azureServiceConnection: $(azureServiceConnection)
                siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                resourceGroupName: $(ResourceGroupName)
                location: $(location)
                siteFarmId: $(siteFarmId)
                siteId:  '$(siteEnvPrefixLocal)$(siteId)'
                siteName: $(siteName)
                uniqueMod: $(uniqueMod)
                buildId: $(Build.BuildId)

            - template: /.devops/pipeline/_deploy-container.yml
              parameters:
                azureServiceConnection: $(azureServiceConnection)
                siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                siteId: '$(siteEnvPrefixLocal)$(siteId)'
                uniqueMod: $(uniqueMod)
                siteFarmId: $(siteFarmId)
                containerRegistry: $(containerRegistry)
                sourceBranchName: $(Build.SourceBranchName)
                tag: 'latest'

      - job: ProcessSites1
        displayName: Process 1 set of sites
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - script: |
              rm -rf $(Build.ArtifactStagingDirectory)/manifest.txt
              touch $(Build.ArtifactStagingDirectory)/manifest.txt

              rm -rf $(Build.ArtifactStagingDirectory)/build-image.txt
              echo $(tag) > $(Build.ArtifactStagingDirectory)/build-image.txt

              cp -r $(Build.SourcesDirectory)/.devops/scripts/trigger-release-infrastructure-pipeline.ps1 $(Build.ArtifactStagingDirectory)
            displayName: 'Initialize drop files'

          - ${{ each site in parameters.sites_1 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"

                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=site;]${{site}}"
                  echo "##vso[task.setvariable variable=siteId;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'

              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName)
                  location: $(location)
                  siteFarmId: $(siteFarmId)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  siteName: $(siteName)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)

              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'

      - job: ProcessSites2
        displayName: Process 2 set of sites
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - script: |
              rm -rf $(Build.ArtifactStagingDirectory)/manifest.txt
              touch $(Build.ArtifactStagingDirectory)/manifest.txt

              rm -rf $(Build.ArtifactStagingDirectory)/build-image.txt
              echo $(tag) > $(Build.ArtifactStagingDirectory)/build-image.txt

              cp -r $(Build.SourcesDirectory)/.devops/scripts/trigger-release-infrastructure-pipeline.ps1 $(Build.ArtifactStagingDirectory)
            displayName: 'Initialize drop files'

          - ${{ each site in parameters.sites_2 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"

                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=site;]${{site}}"
                  echo "##vso[task.setvariable variable=siteId;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'

              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName)
                  location: $(location)
                  siteFarmId: $(siteFarmId)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  siteName: $(siteName)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)

              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'

      - job: ProcessSites3
        displayName: Process 3 set of sites
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - script: |
              rm -rf $(Build.ArtifactStagingDirectory)/manifest.txt
              touch $(Build.ArtifactStagingDirectory)/manifest.txt

              rm -rf $(Build.ArtifactStagingDirectory)/build-image.txt
              echo $(tag) > $(Build.ArtifactStagingDirectory)/build-image.txt

              cp -r $(Build.SourcesDirectory)/.devops/scripts/trigger-release-infrastructure-pipeline.ps1 $(Build.ArtifactStagingDirectory)
            displayName: 'Initialize drop files'

          - ${{ each site in parameters.sites_3 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"

                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=site;]${{site}}"
                  echo "##vso[task.setvariable variable=siteId;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'

              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName)
                  location: $(location)
                  siteFarmId: $(siteFarmId)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  siteName: $(siteName)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)

              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'

      - job: ProcessSites4
        displayName: Process 4 set of sites
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - script: |
              rm -rf $(Build.ArtifactStagingDirectory)/manifest.txt
              touch $(Build.ArtifactStagingDirectory)/manifest.txt

              rm -rf $(Build.ArtifactStagingDirectory)/build-image.txt
              echo $(tag) > $(Build.ArtifactStagingDirectory)/build-image.txt

              cp -r $(Build.SourcesDirectory)/.devops/scripts/trigger-release-infrastructure-pipeline.ps1 $(Build.ArtifactStagingDirectory)
            displayName: 'Initialize drop files'

          - ${{ each site in parameters.sites_4 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"

                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=site;]${{site}}"
                  echo "##vso[task.setvariable variable=siteId;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'

              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName)
                  location: $(location)
                  siteFarmId: $(siteFarmId)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  siteName: $(siteName)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)

              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'

#      - job: ProcessSites5
#        displayName: Process 5 set of sites
#        dependsOn: ['ReadManifest']
#        variables:
#          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
#        steps:
#          - script: |
#              rm -rf $(Build.ArtifactStagingDirectory)/manifest.txt
#              touch $(Build.ArtifactStagingDirectory)/manifest.txt
#
#              rm -rf $(Build.ArtifactStagingDirectory)/build-image.txt
#              echo $(tag) > $(Build.ArtifactStagingDirectory)/build-image.txt
#
#              cp -r $(Build.SourcesDirectory)/.devops/scripts/trigger-release-infrastructure-pipeline.ps1 $(Build.ArtifactStagingDirectory)
#            displayName: 'Initialize drop files'
#
#          - ${{ each site in parameters.sites_5 }}:
#              - script: |
#                  IFS='|'
#                  read -a siteInfo <<< "${{site}}"
#
#                  echo "CountyId: ${siteInfo[0]}"
#                  echo "CountyName : ${siteInfo[2]}"
#                  echo "FarmId : ${siteInfo[1]}"
#                  echo "##vso[task.setvariable variable=site;]${{site}}"
#                  echo "##vso[task.setvariable variable=siteId;]${siteInfo[2]}"
#                  echo "##vso[task.setvariable variable=siteFarmId;]${siteInfo[1]}"
#                  echo "##vso[task.setvariable variable=siteName;]${siteInfo[0]}"
#                  echo "##vso[task.setvariable variable=ResourceGroupName;]-ctcms-df${siteInfo[1]}-app-rg"
#                displayName: 'SITE: ${{ site }}'
#
#              - template: /.devops/pipeline/_provision-app-service.yml
#                parameters:
#                  azureServiceConnection: $(azureServiceConnection)
#                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
#                  resourceGroupName: $(ResourceGroupName)
#                  location: $(location)
#                  siteFarmId: $(siteFarmId)
#                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
#                  siteName: $(siteName)
#                  uniqueMod: $(uniqueMod)
#                  buildId: $(Build.BuildId)
#
#              - template: /.devops/pipeline/_deploy-container.yml
#                parameters:
#                  azureServiceConnection: $(azureServiceConnection)
#                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
#                  siteId: '$(siteEnvPrefixLocal)$(siteId)'
#                  uniqueMod: $(uniqueMod)
#                  siteFarmId: $(siteFarmId)
#                  containerRegistry: $(containerRegistry)
#                  sourceBranchName: $(Build.SourceBranchName)
#                  tag: 'latest'
